on:
  push:
    branches: [ feature* ]

jobs:
  create-feature-pr:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - name: Check PullRequest Exists 
        id: check_pr
        env: 
          HEAD_MESSAGE: ${{ github.event.head_commit.message }}
        run: |
          COMMIT_MESSAGE=$(echo "${HEAD_MESSAGE}" | sed -n -e 1p)
          echo "message=${COMMIT_MESSAGE}" >> "$GITHUB_OUTPUT"
          echo "count=$(gh pr list -S 'テスト in:title' | wc -l)" >> "$GITHUB_OUTPUT"

      - name: Create Test Pull Request
        if: ${{ steps.check_pr.outputs.count == '0' }}
        run: |
          gh pr create \
            -B main \
            -t "テスト ${{ steps.check_pr.outputs.message }}" \
            -a ${{ github.actor }} \
            --body-file ./.github/RELEASE_WORKFLOW_TEMPLATE.md

      - name: Edit Test Pull Request
        if: ${{ steps.check_pr.outputs.count != '0' }}
        run: |
          pr_number=$(gh pr list -S 'テスト in:title' --json number -q '.[0].number')
          old_title=$(gh pr view "$pr_number" --json title -q '.title')
          gh pr edit "$pr_number" -t "${old_title} / ${{ steps.check_pr.outputs.message }}"
