name: pr の取得

on:
  workflow_dispatch:
  
env:
  SLACK_USERNAME: Slack Notify Bot 
  SLACK_WEBHOOK: ${{secrets.SLACK_WEB_HOOK_URL}}


jobs: 
  get-prs:
    runs-on: ubuntu-latest  
    env:
      OWNER: Kai7orz
    steps:
      - name: 情報出力
        uses: actions/checkout@v4
      - run: echo "MY_REPOSITORY=$(basename -s .git $(git remote get-url origin))" >> $GITHUB_ENV
      - run: |
            pr_list=$(gh pr list --repo $OWNER/$MY_REPOSITORY --json title,url,author | jq -c '[.[].author]' )
            echo "value=$pr_list" >> $GITHUB_OUTPUT
            echo "$pr_list"
            echo "$pr_list" | jq -r '.[] | .login' | while read login; do 
              match=$(jq -r --arg login "$login" '.users[] | select(.name == $login)' .github/workflows/users.json)
              echo "users.name -> $.name" 
              echo "login -> $login"
              if [ -n "$match" ]; then 
               echo "☑ users.json matched"
              else
               echo "×"
              fi
            echo "$SLACK_WEBHOOK"
            
            done

        env: 
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN}}
      
      - name: slack通知
        uses: rtCamp/action-slack-notify@v2        
        env:   
          SLACK_TITLE: success 
          SLACK_COLOR: good 
          SLACK_MESSAGE: 動作検証完了☑

        
