name: pr の取得

on:
  workflow_dispatch:

jobs: 
  get-prs:
    runs-on: ubuntu-latest  
    env:
      OWNER: Kai7orz
    steps:
      - name: 情報出力
        uses: actions/checkout@v4
      - run: echo "MY_REPOSITORY=$(basename -s .git $(git remote get-url origin))" >> $GITHUB_ENV
      - run: |
            pr_list=$(gh pr list --repo $OWNER/$MY_REPOSITORY --json title,url,author | jq -c '[.[].author]' )
            echo "$pr_list" >> $GITHUB_OUTPUT

            echo "$pr_list" | jq -c '.[]' | while read aut; do 
              echo "$aut"
            done

      # - run: |
      #       while read user
      #       do 
      #        echo "PR 作成者: ${user} "
      #       done < ${value}

        env: 
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN}}
        

        
