name: pr の取得

on:
  workflow_dispatch:

jobs: 
  get-prs:
    runs-on: ubuntu-latest  
    env:
      OWNER: Kai7orz
    steps:
      - name: 情報出力
        uses: actions/checkout@v4
      - run: echo "MY_REPOSITORY=$(basename -s .git $(git remote get-url origin))" >> $GITHUB_ENV
      - run: |
            pr_list=$(gh pr list --repo $OWNER/$MY_REPOSITORY --json title,url,author | jq -c '[.[].author]' )
            echo "value=$pr_list" >> $GITHUB_OUTPUT

            echo "$pr_list" | jq -c '.[]' | while read aut; do 
              match=$(jq -r --arg login "$login" '.users[] | select(.name == $login)' .github/workflows/users.json)

              if [ -n "$match" ]; then 
               echo "☑ users.json matched"
              else
               echo "×"
              fi
            done

   

        env: 
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN}}
        

        
