name: pr の取得

on:
  workflow_dispatch:

jobs: 
  get-prs:
    runs-on: ubuntu-latest  
    env:
      OWNER: Kai7orz
    steps:
      - name: 情報出力
        uses: actions/checkout@v4
      - run: echo "MY_REPOSITORY=$(basename -s .git $(git remote get-url origin))" >> $GITHUB_ENV
      - run: |
            pr_list=$(gh pr list --repo $OWNER/$MY_REPOSITORY --json title,url | jq '[.[].number]' )
            echo "::set-output name=value::$(echo $pr_list | jq -c .)"
        env: 
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN}}
        
